from django.test import TestCase, RequestFactory
from reviews.views import index

# SimpleTestCase can:
# - Check for exceptions raised by a view function.
# - Test form fields.
# - Includes built-in test client
# - Verify redirect by view function.
# - Match the equality of two HTML, JSON, or XML outputs generated by view functions.

# TransactionTestCase can:
# - Run tests that include database transactions.
# - Reset the database to default state before a test case runs.
# - Skip tests based on database features (great if dev & prod databases differ)

# LiveServerTestCase can:
# - Render's live page versions to test user interaction, etc.


class TestIndexView(TestCase):
    def setUp(self):
        self.factory = RequestFactory()

    def test_index_view(self):
        request = self.factory.get('/index')
        request.session = {}
        response = index(request)
        self.assertEqual(response.status_code, 200)